stages:
  - build
  - deploy

build-job:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
  script:
  - echo "Building application..."
  - docker-compose build
  - echo "Application successfully builded."

deploy-job:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
  script:
    - echo "Deploying application..."
    - docker-compose down
    - docker-compose up -d
    - echo "Application successfully deployed."
